"""
Export the synthetic cohort as a register-style flat file + machine-readable
codebook, so the project hands in a documented "dataset" rather than only code.

Outputs (created under ./data/):
  - synthetic_cohort.csv   : one row per synthetic individual
  - codebook.csv           : variable-level metadata (DST/DREAM-style)

The layout deliberately imitates a Danish administrative register extract
(one person-row, typed variables, a synthetic pseudo-CPR key). NOTHING here is
real personal data; it is generated by early_retirement_savings_model.py.
"""

from __future__ import annotations

import os
import numpy as np
import pandas as pd

from early_retirement_savings_model import (
    Params, FP, RES, STATE_NAMES,
    generate_population, simulate,
)

DATA_DIR = os.path.join(os.path.dirname(__file__), "data")


def build_frame(p: Params) -> pd.DataFrame:
    rng = np.random.default_rng(p.seed)
    pop = generate_population(p, rng)
    res = simulate(p, pop, rng)

    n = pop["age"].size
    df = pd.DataFrame({
        # synthetic pseudo-key (NOT a real CPR; format only resembles one)
        "pnr_synth": [f"SYN{p.seed:02d}{i:06d}" for i in range(n)],
        "age": pop["age"],
        "civilstatus": np.where(pop["is_single"], "enlig", "samlevende"),
        "track": np.where(pop["track"] == RES, "ressourceforloeb", "foertidspension"),
        "benefit_gross_dkk": np.where(
            pop["track"] == RES,
            np.where(pop["is_single"], p.benefit_res_single, p.benefit_res_cohab),
            np.where(pop["is_single"], p.benefit_fp_single, p.benefit_fp_cohab),
        ).astype(int),
        "net_annual_cost_dkk": np.where(pop["track"] == RES,
                                        pop["cost_res"], pop["cost_fp"]).round().astype(int),
        "fp_responsive": pop["responsive"].astype(int),
        "res_years_left": np.where(pop["track"] == RES, pop["res_years_left"], 0),
        "years_to_folkepension": (p.folkepension_age - pop["age"]).astype(int),
        "npv_saving_dkk": res["saving_per_individual"].round().astype(int),
    })
    return df


def codebook() -> pd.DataFrame:
    rows = [
        ("pnr_synth", "string", "Synthetic pseudo-identifier. NOT a real CPR number.", ""),
        ("age", "int", "Age in completed years at simulation start.", "18-30"),
        ("civilstatus", "category", "Cohabitation status driving the benefit rate.", "enlig | samlevende"),
        ("track", "category", "Support track the person starts in.", "foertidspension | ressourceforloeb"),
        ("benefit_gross_dkk", "int", "Annual GROSS public transfer in the start state (DKK).", ">=0"),
        ("net_annual_cost_dkk", "int", "Annual NET public cost = gross x (1 - tax_back) (DKK).", ">=0"),
        ("fp_responsive", "int", "1 if FP work capacity can develop (eligible to exit), else 0.", "0 | 1"),
        ("res_years_left", "int", "Remaining ressourceforløb duration in years (0 if FP track).", "0-5"),
        ("years_to_folkepension", "int", "Years from start age to folkepension age (model horizon).", ">=0"),
        ("npv_saving_dkk", "int", "Monte-Carlo mean NPV of public expenditure avoided, net of programme cost (DKK).", "real"),
    ]
    return pd.DataFrame(rows, columns=["variable", "type", "label", "valid_range"])


def main() -> None:
    p = Params()
    os.makedirs(DATA_DIR, exist_ok=True)

    df = build_frame(p)
    cb = codebook()

    df_path = os.path.join(DATA_DIR, "synthetic_cohort.csv")
    cb_path = os.path.join(DATA_DIR, "codebook.csv")
    df.to_csv(df_path, index=False)
    cb.to_csv(cb_path, index=False)

    print(f"Wrote {len(df):,} synthetic person-rows -> {df_path}")
    print(f"Wrote {len(cb):,} codebook entries     -> {cb_path}")
    print("\nFirst rows:")
    print(df.head(8).to_string(index=False))
    print("\nTrack distribution:")
    print(df["track"].value_counts().to_string())


if __name__ == "__main__":
    main()
